image: ubuntu:latest

stages:
  - deploy

deploy_dev:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - cat ./deploy/known_hosts >> ~/.ssh/known_hosts
   - (umask  077 ; echo $STAGE_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
  script:
    - cat ./deploy/script.sh | ssh -T ubuntu@$STAGE_SSH_HOST
  only:
    - dev