image: ubuntu:latest

build stage job:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - cat ./deploy/known_hosts >> ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
    - (umask  077 ; echo $STAGE_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
    - cat ./deploy/script.sh | ssh -T ubuntu@$STAGE_SSH_HOST
  only:
    - dev