version: "3.8"

networks:
  tourselfer_front_network:

services:
  nginx_front:
    build: 
      args:
        NGINX_HOST: ${HOST}
        NGINX_EMAIL: ${EMAIL}
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_front
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: ${HOST}
      NGINX_EMAIL: ${EMAIL}
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nextjs_front
    networks:
      - tourselfer_front_network
  nextjs_front:
    container_name: nextjs_front
    build:
      context: ./
      dockerfile: ./docker/nextjs/Dockerfile
    env_file:
      - .env
    networks:
      - tourselfer_front_network