import React from 'react';
import {Breadcrumbs, Layout} from '@components/common';
import Head from 'next/head';
import {Button} from '@components/ui';
import {ArrowLeft, ArrowRight, Heart, Minus, Plus, Star, User} from '@components/icons';

export default function ExampleButtons() {
    const [loading, setLoading] = React.useState(false);
    function handleClick() {
        setLoading(true);
    }

    const style = {margin: '8px'};
    
    return (
        <Layout>
            <Head>
                <title>Buttons</title>
            </Head>

            <div className="container examples">
                <Breadcrumbs/>
                <h1 className="title-1">Buttons</h1>

                <div style={{margin: "1em 0"}}>
                    <label className="checkbox">
                        <input className="checkbox__input" type="checkbox"
                               checked={loading}
                               onChange={() => setLoading(!loading)}
                        />
                        <span className="checkbox__label">Toggle loading</span>
                    </label>
                </div>

                <div>
                    <Button
                        style={style}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Default
                    </Button>
                    <Button
                        style={style}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Default
                    </Button>
                    <Button
                        style={style}
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Default
                    </Button>
                    <Button
                        style={style}
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>

                <div>
                    <Button
                        style={style}
                        variant='filled'
                        squared={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Squared
                    </Button>
                    <Button
                        style={style}
                        variant='filled'
                        squared={true}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Squared
                    </Button>
                    <Button
                        style={style}
                        variant='filled'
                        squared={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Squared
                    </Button>
                    <Button
                        style={style}
                        variant='filled'
                        squared={true}
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Squared
                    </Button>
                    <Button
                        style={style}
                        variant='filled'
                        squared={true}
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>

                <div>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        colored={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        colored={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        colored={true}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        colored={true}
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        colored={true}
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        colored={true}
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        colored={true}
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>

                <div>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        colored={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        colored={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        colored={true}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        colored={true}
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        colored={true}
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        colored={true}
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        colored={true}
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>

                <div>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="large"
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>

                <div>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        isEndIcon={true}
                        endIcon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        isStartIcon={true}
                        startIcon={<Plus/>}
                        disabled={true}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Disabled
                    </Button>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                    <Button
                        style={style}
                        variant="filled"
                        size="medium"
                        isIcon={true}
                        icon={<Plus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>

                <div>
                    <Button
                        style={style}
                        variant="filled"
                        size="large"
                        colored={true}
                        isStartIcon={true}
                        startIcon={<Heart/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Large
                    </Button>
                    <Button
                        style={style}
                        variant='filled'
                        size="medium"
                        isEndIcon={true}
                        endIcon={<Star/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        variant="outlined"
                        size="medium"
                        squared={true}
                        isStartIcon={true}
                        startIcon={<ArrowLeft/>}
                        isEndIcon={true}
                        endIcon={<ArrowRight/>}
                        loading={loading}
                        onClick={handleClick}
                    >
                        Medium
                    </Button>
                    <Button
                        style={style}
                        size="medium"
                        squared={true}
                        isIcon={true}
                        icon={<Minus/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                    <Button
                        style={style}
                        isIcon={true}
                        icon={<User/>}
                        loading={loading}
                        onClick={handleClick}
                    />
                </div>
            </div>
        </Layout>
    );
}